name: moonwallet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_web3_webview: ^0.1.2
  flutter_inappwebview: ^6.1.5
  flutter_feather_icons: ^2.0.0
  shared_preferences: ^2.4.0 
  font_awesome_flutter: ^10.8.0
  lucide_icons_flutter: ^1.2.6
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  logger: ^2.5.0
  giffy_dialog: ^2.3.0
  imgx: ^0.1.4
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32: ^2.0.0
  pinput: ^5.0.1
  encrypt: ^5.0.3
  ulid: ^2.0.1
  vibration: ^3.1.2
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  custom_cached_image: ^1.0.5

  k_chart_plus_deeping: ^1.0.2-5.2.2.3
  qr_flutter: ^4.1.0
  awesome_snackbar_content: ^0.1.5
  intl: ^0.20.2
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  mobile_scanner: ^6.0.6
  fast_cached_network_image: ^1.3.3+5
  memory_cache: ^1.2.0
  delightful_toast: ^1.1.0
  currency_formatter: ^2.2.2
  internet_connection_checker_plus: ^2.7.1
  hex: ^0.2.0
  http: ^1.3.0
  crypto: ^3.0.6
  clipboard: ^0.1.3
  uuid: ^4.5.1
  pointycastle: ^3.9.1
  modal_bottom_sheet: ^3.0.0
  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.5
  eth_sig_util: ^0.0.9
  objectbox: ^4.1.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  device_info_plus: ^11.3.3
  liquid_pull_to_refresh: ^3.0.1
  photo_view: ^0.15.0
  timer_builder: ^2.0.0
  skeletonizer: ^1.4.3
  simple_gesture_detector: ^0.2.1
  dio: ^5.8.0+1
  loading_animation_widget: ^1.3.0
  bottom_sheet_scroll_physics: ^1.0.0
  smart_alert_dialog: ^4.0.4
  pull_to_refresh_flutter3: ^2.0.2
  share_plus: ^10.1.4
  cronet_http: ^1.3.3
  custom_refresh_indicator: ^4.0.1
  cherry_toast: ^1.12.0
  jazzicon: ^1.1.0
  internet_connection_checker: ^3.0.1
  smooth_list_view: ^2.0.2
  flutter_riverpod: ^2.6.1
  web_socket_channel: ^2.4.0
  flashy_tab_bar2: ^0.0.10
  flutter_skeleton_ui: ^0.0.6
  elegant_nav_bar: ^0.0.22
  salomon_bottom_bar: ^3.3.2
  moment_dart: ^5.1.0
  animated_toggle_switch: ^0.8.4
  page_transition: ^2.2.1
  cached_network_image: ^3.4.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  syncfusion_flutter_sliders: ^29.1.39
  bip39_mnemonic: ^3.0.9







  
dependency_overrides:
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/main/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
 color: "#5271ff"
 image: "assets/icon/icon4.png"
 color_dark: "#5271ff"
 image_dark: "assets/icon/icon4.png"
 android_12:
  image: "assets/icon/icon4.png"
  image_dark: "assets/icon/icon4.png"


  color: "#5271ff"
  icon_background_color: "#5271ff"
  color_dark: "#5271ff"





# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: roboto_reg
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        
  assets:
  - assets/4.png
  - assets/b1.webp
  - assets/image.png
  - assets/g2.gif
  - assets/blur1.png
  - assets/blur/blur.png
  - assets/icon/icon4.png
  - assets/logo/png/v_b.png
  - assets/logo/png/vault_1.png
  - assets/logo/png/vault2.png
  - assets/logo/png/v_png.png
  - assets/logo/png/v_t.png
  - assets/logo/png/v_t2.png


  - assets/i1.png
  - assets/bnb.png
  - assets/sonic.png

  - assets/bg/i2.png
  - assets/pro/image.png
  - assets/logos/usdt2.png
  - assets/logos/bitcoin.png
  - assets/logos/eth.png
  - assets/logos/pol.webp
  - assets/web3/ethers.min.js



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
